"""add category to pantry_items

Revision ID: 4a2382a005e1
Revises: 9628a43e3101
Create Date: 2026-07-05 22:03:50.110684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2382a005e1'
down_revision = '9628a43e3101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry_items', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
