"""add_exclude_from_recipes_to_pantry_items

Revision ID: e59ab188b602
Revises: 4a2382a005e1
Create Date: 2026-07-06 15:48:22.939624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59ab188b602'
down_revision = '4a2382a005e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'exclude_from_recipes', sa.Boolean(), nullable=False,
            server_default=sa.text('false'),
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry_items', schema=None) as batch_op:
        batch_op.drop_column('exclude_from_recipes')

    # ### end Alembic commands ###
